version: '3.7'

# All Antara coins need these params
x-zcash-params-volume:
  &zcash-params
  type: bind
  source: /home/smk762/.zcash-params
  target: /home/komodian/.zcash-params

services:
  kmd:
    init: true
    network_mode: "host"
    stop_signal: SIGTERM
    stop_grace_period: 45s
    entrypoint: ["/home/komodian/launch_KMD.sh"]
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.komodod
      args:
        - USER_ID=$USER_ID
        - GROUP_ID=$GROUP_ID
        - COMMIT_HASH=156dba6
    ports:
      - "127.0.0.1:7770:7770"
      - "127.0.0.1:7771:7771"
    volumes:
      - ./code:/home/komodian/code
      - /home/smk762/.komodo:/home/komodian/.komodo
      - /home/smk762/.zcash-params:/home/komodian/.zcash-params
    shm_size: '2gb'
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    healthcheck:
      test: ["CMD", "bash", "/usr/local/bin/healthcheck.sh", "komodo-cli"]
      interval: 15m
      timeout: 60s
      retries: 3
      start_period: 15m

  mm2:
    restart: always
    build: 
      context: mm2
      dockerfile: Dockerfile
      shm_size: '2gb'
    volumes:
      - ./mm2:/home/komodian/mm2
    environment:
      - userpass=${userpass}
    ports:
      - "7783:7783"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  db:
    image: postgres
    restart: always
    shm_size: '2gb'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - kmd
      - mm2
    ports:
      - "7654:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    
  web:
    build: 
      context: .
      shm_size: '2gb'
      args:
        requirements: requirements/dev.txt
    environment:
      - DJANGO_SETTINGS_MODULE=kmd_ntx_stats.settings.dev
    command: bash -c "python manage.py runserver 0.0.0.0:8762 && /code/scripts/collect_seednode_stats.py start"
    restart: always
    volumes:
      - ./code:/code
      - /var/www/stats.kmd.io/html/static:/var/www/stats.kmd.io/html/static
    ports:
      - "8762:8762"
    depends_on:
      - mm2
      - db
      - kmd
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.1/16
