name: Django CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        defaults:
            run:
                shell: bash
                working-directory: code

        runs-on: ubuntu-latest
        strategy:
          max-parallel: 4
          matrix:
            python-version: [3.8]
            
        services:
            db:
                image: postgres
                env:
                    POSTGRES_DB: postgresdb
                    POSTGRES_USER: postgresuser
                    POSTGRES_PASSWORD: postgrespw
                ports: ["5432:5432"]

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                    python-version: 3.8
            - name: Install Dependencies
              run: |
                    sudo apt-get install python3-dev build-essential libpq-dev libgnutls28-dev gcc default-libmysqlclient-dev build-essential python3-mysql.connector python3-pip libcurl4-openssl-dev libssl-dev -y
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
            - name: Run Migrations
              run: python manage.py migrate
              env: 
                    DBENGINE: django.db.backends.mysql
                    DBNAME: postgresdb
                    DBUSER: postgresuser
                    DBPASSWORD: postgrespw
                    DBHOST: 127.0.0.1
                    DBPORT: 5432
            - name: Run Tests
              run: |
                    python manage.py test
              env: 
                    DBENGINE: django.db.backends.postgresql
                    DBNAME: postgresdb
                    DBUSER: postgresuser
                    DBPASSWORD: postgrespw
                    DBHOST: 127.0.0.1
                    DBPORT: 5432
                
            - name: Python Django Coverage GitHub Action
                # You may pin to the exact commit or the version.
                # uses: dc740/django-coveragepy-github-action@f8581a749bd8cf75838b120a6aa07dc40a060e61
              uses: dc740/django-coveragepy-github-action@0.9
              with:
                    # Application
                    #django-app: # optional, default is 
                    # Minimum allowed code coverage
                    minimum-coverage: 10 # optional, default is 10

            - name: Django Security Check
              # You may pin to the exact commit or the version.
              # uses: victoriadrake/django-security-check@762dd0ab80194dbded70117daa32bd7d139c6a04
              uses: victoriadrake/django-security-check@v1.1.0
                
            - name: pytest-django-action
              # You may pin to the exact commit or the version.
              # uses: samwlms/pytest-django-action@1671ce1d99cb86eb7b76f0e7639150955614162d
              uses: samwlms/pytest-django-action@1.9
