name: Django CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        defaults:
            run:
                shell: bash
                working-directory: code

        runs-on: ubuntu-latest
        strategy:
          max-parallel: 4
          matrix:
            python-version: [3.8]
            
        services:
            db:
                image: postgres
                env:
                    POSTGRES_DB: postgresdb
                    POSTGRES_USER: postgresuser
                    POSTGRES_PASSWORD: postgrespw
                ports: ["5432:5432"]

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                    python-version: 3.8
            - name: Install Dependencies
              run: |
                    sudo apt-get install python3-dev build-essential libpq-dev libgnutls28-dev gcc default-libmysqlclient-dev build-essential python3-mysql.connector python3-pip libcurl4-openssl-dev libssl-dev -y
                    python -m pip install --upgrade pip
                    pip install -r requirements/test.txt
                    
            - name: Run Migrations
              run: python manage.py migrate
              env: 
                    DBENGINE: django.db.backends.mysql
                    DBNAME: postgresdb
                    DBUSER: postgresuser
                    DBPASSWORD: postgrespw
                    DBHOST: 127.0.0.1
                    DBPORT: 5432
                    SYSTEM_ENV: GITHUB_WORKFLOW
                    DJANGO_SETTINGS_MODULE: kmd_ntx_stats.test
                    SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
                    
            - name: Run Tests
              run: |
                    python manage.py test
              env: 
                    DBENGINE: django.db.backends.postgresql
                    DBNAME: postgresdb
                    DBUSER: postgresuser
                    DBPASSWORD: postgrespw
                    DBHOST: 127.0.0.1
                    DBPORT: 5432
                    DJANGO_SETTINGS_MODULE: kmd_ntx_stats.test
                    SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

            - name: Run Tests 2
              run: |
                    py.test -vvl;
              env: 
                    DBENGINE: django.db.backends.postgresql
                    DBNAME: postgresdb
                    DBUSER: postgresuser
                    DBPASSWORD: postgrespw
                    DBHOST: 127.0.0.1
                    DBPORT: 5432
                    DJANGO_SETTINGS_MODULE: kmd_ntx_stats.test
                    SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
