name: Django CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:

        runs-on: ubuntu-latest
        strategy:
          max-parallel: 4
          matrix:
            python-version: [3.7]
            
        services:
            db:
                image: postgres
                restart: always
                environment:
                    - POSTGRES_DB=postgresdb
                    - POSTGRES_USER=postgresuser
                    - POSTGRES_PASSWORD=postgrespw
                depends_on:
                    - mm2
                ports:
                    - "5432:5432"
                logging:
                    driver: "json-file"
                    options:
                    max-size: "20m"
                    max-file: "10"

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python $
                  uses: actions/setup-python@v2
                  with:
                    python-version: $
            - name: Install Dependencies
                  run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
            - name: Run Migrations
                  run: python manage.py migrate
                  env: 
                    DBENGINE: django.db.backends.mysql
                    DBNAME: postgresdb
                    DBUSER: postgresuser
                    DBPASSWORD: postgrespw
                    DBHOST: 127.0.0.1
                    DBPORT: $
            - name: Run Tests
                  run: |
                    python manage.py test
                  env: 
                    DBENGINE: django.db.backends.postgresql
                    DBNAME: postgresdb
                    DBUSER: postgresuser
                    DBPASSWORD: postgrespw
                    DBHOST: 127.0.0.1
                    DBPORT: $
                
            - name: Python Django Coverage GitHub Action
                # You may pin to the exact commit or the version.
                # uses: dc740/django-coveragepy-github-action@f8581a749bd8cf75838b120a6aa07dc40a060e61
                uses: dc740/django-coveragepy-github-action@0.9
                with:
                    # Application
                    #django-app: # optional, default is 
                    # Minimum allowed code coverage
                    minimum-coverage: 10 # optional, default is 10

            - name: Django Security Check
                # You may pin to the exact commit or the version.
                # uses: victoriadrake/django-security-check@762dd0ab80194dbded70117daa32bd7d139c6a04
                uses: victoriadrake/django-security-check@v1.1.0
                
            - name: pytest-django-action
                # You may pin to the exact commit or the version.
                # uses: samwlms/pytest-django-action@1671ce1d99cb86eb7b76f0e7639150955614162d
                uses: samwlms/pytest-django-action@1.9
