name: Django CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        defaults:
            run:
                shell: bash
                working-directory: code

        runs-on: ubuntu-latest
        strategy:
          max-parallel: 4
          matrix:
            python-version: [3.8]
            
        services:
            db:
                image: postgres
                env:
                    POSTGRES_DB: postgres
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                options: >-
                  --health-cmd pg_isready
                  --health-interval 10s
                  --health-timeout 5s
                  --health-retries 5

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                    python-version: 3.8
            - name: Install Dependencies
              run: |
                    sudo apt-get install python3-dev build-essential libpq-dev libgnutls28-dev gcc default-libmysqlclient-dev build-essential python3-mysql.connector python3-pip libcurl4-openssl-dev libssl-dev -y
                    python -m pip install --upgrade pip
                    pip install -r requirements/test.txt
                    
            - name: Run Migrations
              run: python manage.py migrate
              env: 
                    POSTGRES_HOST: db
                    POSTGRES_PORT: 5432
                    DBENGINE: django.db.backends.postgresql
                    DBNAME: postgres
                    DBUSER: postgres
                    DBPASSWORD: postgres
                    DBHOST: 127.0.0.1
                    DBPORT: 5432
                    SYSTEM_ENV: GITHUB_WORKFLOW
                    DJANGO_SETTINGS_MODULE: kmd_ntx_stats.settings.test
                    DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
                    SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
                    
            - name: Run Tests
              run: |
                    python manage.py test
              env: 
                    POSTGRES_HOST: db
                    POSTGRES_PORT: 5432
                    DBENGINE: django.db.backends.postgresql
                    DBNAME: postgres
                    DBUSER: postgres
                    DBPASSWORD: postgres
                    DBHOST: 127.0.0.1
                    DBPORT: 5432
                    SYSTEM_ENV: GITHUB_WORKFLOW
                    DJANGO_SETTINGS_MODULE: kmd_ntx_stats.settings.test
                    DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
                    SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

            - name: Run Tests 2
              run: |
                    py.test -vvl;
              env: 
                    POSTGRES_HOST: db
                    POSTGRES_PORT: 5432
                    DBENGINE: django.db.backends.postgresql
                    DBNAME: postgres
                    DBUSER: postgres
                    DBPASSWORD: postgres
                    DBHOST: 127.0.0.1
                    DBPORT: 5432
                    SYSTEM_ENV: GITHUB_WORKFLOW
                    DJANGO_SETTINGS_MODULE: kmd_ntx_stats.settings.test
                    DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
                    SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
